- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20240526102231171500000012.cb6iyisc4ryw.us-east-1.rds.amazonaws.com" 
    login_user: "temitayo"
    login_password: "tayo12345"
    name: temitayodb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20240526102231171500000012.cb6iyisc4ryw.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "temitayo" }
    - { regexp: '^database_name_here', line: "temitayodb" }
    - { regexp: '^password_here', line: "tayo12345" }
