- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20240526171559442400000012.cb6iyisc4ryw.us-east-1.rds.amazonaws.com"
    login_user: "temitayo"
    login_password: "tayo12345"
    name: temitayodb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20240526171559442400000012.cb6iyisc4ryw.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "temitayo" }
    - { regexp: '^tooling', line: "temitayodb" }
    - { regexp: '^admin', line: "tayo12345" }


